services:
  airlines:
    build:
      context: ./airlines
    ports:
      - "8080:8080"
    networks:
      - observability

  flights:
    build:
      context: ./flights
    ports:
      - "5003:5003"
    networks:
      - observability

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - observability
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  observability:
    external: true